"Find euclidean distances for all songs and try it with different features."

In [2]:
#1. Import Modules:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics.pairwise import euclidean_distances

In [3]:
#2.Read .csv, clean csv from useless DataTypes, nail the job:
tensongs = pd.read_csv(r'df_audio_features_10.csv')
tensongs # see what to drop
# Drop columns with shitty DataTypes:
somecolumnswereshit = tensongs[["danceability", "energy", "loudness", "speechiness", "acousticness", "instrumentalness", "liveness", "valence", "tempo", "duration_ms"]]
somecolumnswereshit #see if it works
# Tried to insert songnames as index, but failed
epicsolution = pd.DataFrame(euclidean_distances(somecolumnswereshit), index=somecolumnswereshit.index, columns=somecolumnswereshit.index)
epicsolution
# gg ez

,0,1,2,3,4,5,6,7,8,9
0,0.000000,14573.008289,86373.004024,19214.006953,96506.007932,49851.008398,139947.000719,94967.000737,188973.011453,30346.063953
1,14573.008289,0.000000,71800.011435,33787.011459,81933.018075,64424.015061,154520.002592,109540.002803,174400.007754,15773.071995
2,86373.004024,71800.011435,0.000000,105587.000950,10133.013478,136224.000197,226320.000340,181340.000693,102600.034253,56027.060661
3,19214.006953,33787.011459,105587.000950,0.000000,115720.003978,30637.006573,120733.000183,75753.000175,208187.011705,49560.047051
4,96506.007932,81933.018075,10133.013478,115720.003978,0.000000,146357.000380,236453.001515,191473.002481,92467.054223,66160.073217
5,49851.008398,64424.015061,136224.000197,30637.006573,146357.000380,0.000000,90096.001465,45116.004565,238824.016873,80197.048206
6,139947.000719,154520.002592,226320.000340,120733.000183,236453.001515,90096.001465,0.000000,44980.000192,328920.008328,170293.015161
7,94967.000737,109540.002803,181340.000693,75753.000175,191473.002481,45116.004565,44980.000192,0.000000,283940.008596,125313.018301
8,188973.011453,174400.007754,102600.034253,208187.011705,92467.054223,238824.016873,328920.008328,283940.008596,0.000000,158627.000245
9,30346.063953,15773.071995,56027.060661,49560.047051,66160.073217,80197.048206,170293.015161,125313.018301,158627.000245,0.000000